application: gofr-io
version: prod
runtime: go
api_version: go1

handlers:
- url: /content
  static_dir: content
  expiration: "1d"
- url: /(favicon\.ico)
  static_files: content/\1
  upload: content/(.*)
- url: /tasks/.*
  script: _go_app
  login: admin
- url: /cron/.*
  script: _go_app
  login: admin
- url: /
  script: _go_app
- url: /.*
  script: _go_app
  login: required
