application: gofr
version: 1
runtime: go
api_version: go1

handlers:
- url: /content
  static_dir: content
- url: /tasks/.*
  script: _go_app
  login: admin
- url: /.*
  script: _go_app
  login: required
